delfick/photons

- apps/interactor/docker/harpoon.yml
This change should also remove the need to squash the final image as I've merged the two `RUN` directives into one.
> Rearranging the container image build steps to reduce image size

- modules/photons_control/addon.py
This resolves #27 by sorting the list of found devices prior to any of the enabled outputs.
> Switched find_ips to sort by IP address for all outputs. 

- apps/interactor/command
- apps/interactor/docker/harpoon.yml
- apps/interactor/interactor/addon.py
Added a healthcheck task to Interactor that issues a status
command to Interactor and returns the status via exit code.
This commit also fixes and improves the included command script
by adding a task to return the configured bind address and by
adding curl to the image.
This resolves #23 
This resolves #29
> [interactor] Enable Docker container health status

- apps/interactor/interactor/addon.py
The EL8-based distros like RHEL, CentOS and Oracle Linux default
to Python 3.6. This fix allows the Interactor RPM to build for those
platforms.
Fixes #39.
> [bug] Python 3.6 doesn't support await in fstrings

- apps/interactor/interactor/addon.py
I'm not sure if the task name change was deliberate, but folks
may have existing scripts or systemd units that use the old task
name and breaking that is bad juju.
This also fixes the container image which is currently broken as
it also uses "lan:interactor" as the task name.
Fixes #49 
> [interactor] Rename the Interactor task back to [lan:]interactor

- apps/interactor/docs/docker.rst
> I _think_ the rst link syntax is correct, but please confirm (and delete this comment) prior to merging. :) 
Updated the note to let folks know that while bulb discovery may not
work, the rest of Interactor does. Also, removed the version from
the image (so it always pulls latest) and wrapped the variable in
quotes to avoid possible expansion issues.
> [docs] Interactor works on macOS and Windows with hardcoded discovery

- apps/interactor/interactor/commander/commands/effects.py
- apps/interactor/tests/commander/commands/test_effects.py
This exposes the power_on argument so that users can stop effects
when the devices are soft off.
This resolves issue #64 (or at least the initial request) which is to prevent a device from powering on.
> feat: add matrix and linear options to effects/stop

- apps/interactor/tests/commander/commands/test_control.py
- apps/interactor/tests/commander/commands/test_effects.py
- apps/interactor/tests/commander/commands/test_scenes.py
- apps/interactor/tests/conftest.py
- modules/photons_app/mimic/__init__.py
- modules/photons_app/mimic/operators/device.py
Note that switches aren't handled properly and that will be fixed in
future PRs and the tests adjusted accordingly
* No label detection
* Scenes don't see switches
This is first PR to replace https://github.com/delfick/photons/pull/87
> interactor: add a switch to the tests

- modules/photons_control/device_finder.py
- modules/tests/photons_control_tests/device_finder/test_device.py
cap should be for a Capability object rather than a list of strings
This change has no external change as people aren't likely working
directly with these objects and I've made as_dict return the abilities
array named as cap like it currently is
> control: letting device finder device have spot for cap

- apps/interactor/tests/conftest.py
- modules/photons_control/device_finder.py
- modules/tests/photons_control_tests/device_finder/test_filter.py
- modules/tests/photons_control_tests/device_finder/test_information_retrieval.py
Does this such that only non lights (switches) get a GetLabel and real
lights only get a GetColor message
> control: let device_finder get labels from switches

- modules/photons_control/planner/plans.py
- modules/tests/photons_control_tests/planner/test_default_plans.py
Things that aren't lights don't have color and should be skipped
PR 2 to replace #89
> planner: make ColorsPlan understand non lights

- modules/photons_app/photons_app.py
- modules/photons_app/registers.py
- modules/tests/photons_app_tests/test_collector.py
- modules/tests/photons_app_tests/test_registers.py
I noticed this while trying to debug some circular dependencies I'd created in my downstream project.
> fix: the spelling of resolver in various places

- modules/setup.py
- tools/black
This is needed in order to use lifx-photons-core as a dependency
for a Home Assistant custom components. Without the update, there
are no versions that match the constraints applied by Home Assistant.
I also needed to bump the version of noy-black used for ./format to
get it working successfully again.
> ci: update lru-dict and bitarray dependecies to newer versions

- apps/interactor/interactor/commander/commands/effects.py
- modules/photons_control/multizone.py
- modules/tests/photons_control_tests/test_multizone.py
Includes an update to the docs for both the task and Interactor
command to provide a little more clarity on how to set this and
other options.
Also updated the test for this effect.
> control: add support for setting the direction of the MOVE effect

- modules/photons_app/helpers.py
Because sometimes you really need an old fashioned, down-to-earth, no-nonsense `dict`.
> [helpers] add as_dict() method to hp.Firmware

- .gitignore
This aligns our `.gitignore` with the one provided by GitHub for new repos that chose Python as the primary language.
Also, because I use PyENV and Poetry a lot, it'll save me a ton of effort because I keep forgetting to not commit those bits.
> Upedate .gitignore to cover more python variations

- modules/setup.py
> deps: bump lru-dict version to match Home Assistant's minimum required version

- modules/photons_products/registry.py
They were added to the official JSON file yesterday.
> products: add registry entries for Neon and String

- modules/photons_control/tile.py
- modules/photons_messages/enums.py
- modules/photons_messages/fields.py
- modules/photons_messages/messages.py
- tools/generate_photons_messages/_generate
- tools/generate_photons_messages/adjustments.yml
- tools/generate_photons_messages/generate
~Note that the `TileEffectSkyType` enum is currently missing from the published protocol and needs to be added manually until LIFX add it themselves.~
The `TileEffectSkyType` enum has been added upstream.
> Add support for the new SKY firmware effect available on LIFX Ceiling devices

- modules/photons_products/registry.py
The product names are different from the friendly names used in the upstream `products.json` but match the model names used by the LIFX smartphone app. 
I checked with LIFX via email and they asked me to use the friendly names "LIFX Candle Color", "LIFX Candle Colour" and "LIFX Tube".
> products: add LIFX Candle (B10) and LIFX Tube (T10)

- modules/photons_products/registry.py
This PR add supports for the [LIFX Luna LED Lamp](https://www.lifx.com/products/luna).
Values are taken from [upstream products json](https://github.com/LIFX/products/blob/master/products.json).
> products: add support for LIFX Luna

- .github/workflows/ci.yml
- modules/photons_app/mimic/operators/multizone.py
- modules/photons_messages/messages.py
- modules/tests/photons_app_tests/mimic/test_public_protocol.py
- modules/tests/photons_control_tests/test_multizone.py
- tools/generate_photons_messages/adjustments.yml
Fix for https://github.com/delfick/photons/discussions/139
Prior to this photons was not aware of multizone devices with more than 82 zones. This change makes it so that photons can wait for multiple state messages from such devices when using extended multiezone messages.
> Make photons aware it's possible to get multiple extended multi zone state messages
